name: flutterui100day
description: 100 Day UI Flutter Application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^1.3.12
  page_transition: ^1.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/JPEG/

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Black.ttf
          weight: 900
        - asset: fonts/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/Rubik-Light.ttf
          weight: 100
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/Rubik-Regular.ttf
          weight: 400
